# Generated by Django 4.1.3 on 2022-11-30 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_remove_issue_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
